### ISSUE TITLE
Footer / Update social links

### ISSUE THREAD

**Issue by polinamarchenko** [GYMHIT/website#17]
Please update social links 
for twitter:
https://twitter.com/joingymhit?lang=en

for facebook:
https://www.facebook.com/JoinGymHit/

for instagram:
https://www.instagram.com/joingymhit/

for linkedin: 
https://www.linkedin.com/company/gymhit

**Comment by philippschulte** [comment]
@polinamarchenko I have updated all social media links in the footer!
